# docker compose up --build

services:
  web:
    #  Build the image from the Dockerfile.
    build: .
    container_name: we-move
    ports:
      - "5000:5000"
    environment:
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      FLASK_APP: app
      FLASK_ENV: production
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app
    command: python -m flask run --host=0.0.0.0 --port=5000
